### ISSUE TITLE
Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.12.4:test

### ISSUE THREAD

**Issue by pravato** [dequelabs/axe-selenium-java#18]
I am not able to run the example in my environment, I get the following errors:

```
at org.junit.Assert.fail(Assert.java:88)
at com.deque.axe.ExampleTest.testAccessibility(ExampleTest.java:69)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)

[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.12.4:test (default-test) on project axe-selenium: There are test failures.
[ERROR]
[ERROR] Please refer to C:\Users\mpravato\IdealProjects\axe-selenium-java-develop\target\surefire-reports for the individual test results.
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
```

I have updated all the plugins, added some others, after consultations and it still does not work.

**Comment by stephenmathieson** [comment]
Which assertion is failing? The provided stack trace doesn't quite explain the issue you're seeing.

**Comment by stephenmathieson** [comment]
Closing for now. If you're still experiencing this problem, please feel free reopen with reproduction steps.
