### ISSUE TITLE
Getting error on using the ExampleTest

### ISSUE THREAD

**Issue by ershikhar** [dequelabs/axe-selenium-java#5]
Hello ,

Please let me know if you can locate the issue.

I renamed ExampleTest and changed the url to google.com but the script is failing on the line-
JSONObject responseJSON = new AXE.Builder(driver, scriptUrl).analyze();

as you can see in the trace below - 

java.lang.RuntimeException: java.lang.NullPointerException
    at com.deque.axe.AXE.getContents(AXE.java:53)
    at com.deque.axe.AXE.inject(AXE.java:70)
    at com.deque.axe.AXE$Builder.<init>(AXE.java:237)
    at com.deque.axe.Test1.testAccessibility(Test1.java:67)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:601)
    at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
    at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
    at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
    at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
    at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
    at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
    at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:55)
    at org.junit.rules.RunRules.evaluate(RunRules.java:20)
    at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
    at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
    at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
    at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
    at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
    at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
    at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
    at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
    at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:675)
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)
Caused by: java.lang.NullPointerException
    at com.deque.axe.AXE.getContents(AXE.java:44)
    ... 30 more

**Comment by acodebreaker** [comment]
same here , anyone solved it ?

**Comment by zodgevaibhav** [comment]
Please confirm once that axe.min.js file is kept at test\resource folder. I also faced this issues because I made typo in file name.

Let me know if it works :)

**Comment by dmfay** [comment]
Closing due to inactivity.

**Comment by Manu22796** [comment]
Any Solution for this ?? I also facing same problem ,
